export { ManagerHomePage } from './ManagerHomePage'
export { ManagerCompliancePage } from './ManagerCompliancePage'
export { ManagerDefectsPage } from './ManagerDefectsPage'
export { ManagerEquipmentPage } from './ManagerEquipmentPage'
export { ManagerEquipmentDetailPage } from './ManagerEquipmentDetailPage'
