export { SupervisorHomePage } from './SupervisorHomePage'
export { SupervisorReviewsPage } from './SupervisorReviewsPage'
export { SupervisorReviewDetailPage } from './SupervisorReviewDetailPage'
export { SupervisorActionsPage } from './SupervisorActionsPage'
export { SupervisorActionDetailPage } from './SupervisorActionDetailPage'
