export { InspectorHomePage } from './InspectorHomePage'
export { InspectorScanPage } from './InspectorScanPage'
export { EquipmentConfirmationPage as InspectorEquipmentPage } from './EquipmentConfirmationPage'
export { InspectionChecklistPage as InspectorInspectionPage } from './InspectionChecklistPage'
export { InspectionReviewPage } from './InspectionReviewPage'
export { InspectionResultPage } from './InspectionResultPage'
export { InspectorHistoryPage } from './InspectorHistoryPage'
export { InspectorProfilePage } from './InspectorProfilePage'
